version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    working_directory: ~/web

    docker:
      - image: circleci/node:15.7

    steps:
      - checkout
      - run: npm install
      - run: node src/js/helloCircleci.js
      - run: npm run build

workflows:
  node-tests:
    jobs:
      - build
