version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    working_directory: ~/web

    docker:
      - image: circleci/node:9.9

    steps:
      - checkout
      - run: echo hello-circleci

workflows:
  node-tests:
    jobs:
      - build
