version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:15.7
    working_directory: ~/web
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/web
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.9.2
    working_directory: ~/web

    steps:
      - attach_workspace:
          at: ~/web

      - run: sudo pip install awscli
      - run: aws s3 sync ./build s3://webpack-dist-sample/web

workflows:
  node-tests:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
